cni.go
cni_test.go
errors.go
opts.go

1) Splitting config load from init. Added another API Load that
loads the cni config. Added LoadOptions to load from different
sources like .conf file,.conflist file, config as bytes in addition
to default config from the configured cni directory
2) Added locks to protect the networks during status checks and loads
and other parallel access.
3) Added checks for status before setup and remove actions
4) Minor clean up and test case update
Signed-off-by: abhi <abhi@docker.com>

Fixes and cleanups to support different use cases

---

README.md
cni.go
cni_test.go
opts.go

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

Same Opt API for Load and New

---

cni.go
opts.go

Signed-off-by: Abhinandan Prativadi <abhi@docker.com>

Minor cleanup with concurrency and locking

---

cni.go

Some background about why this is needed:
* https://github.com/containerd/cri/issues/948
* https://github.com/containernetworking/plugins/issues/210
Signed-off-by: Lantao Liu <lantaol@google.com>

Ignore "no such file or directory" error.

---

cni.go
cni_test.go

See issue https://github.com/containerd/cri/issues/979
This PR adds a get api to retrive the CNI plugin configuration information for debug / service purposes.
@Random-Liu @abhi 
Signed-off-by: Mike Brown <brownwm@us.ibm.com>

adds a get for the plugin config details

---

errors.go
opts.go

Fix typos in comment: 
1. "intialized" to "initialized" in line 16.
2. "initalized" to "initialized" in line 58.

Fix some typos in comment

---

cni.go
result.go

For https://github.com/containerd/cri/issues/1078.
Slow `Setup` or `Remove` blocks `Status` and `Load` unnecessarily. This PR changes locking location to avoid that.
Signed-off-by: Lantao Liu <lantaol@google.com>

Avoid `Status` lockup during setup and remove.

---

opts.go

This opt allows you to provide the interface name's index with the
configuration.
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

Add WithConfIndex opt

---

namespace_opts.go
types.go

Kubernetes added support for traffic shaping (https://github.com/kubernetes/kubernetes/pull/63194/files) in order to implement traffic shaping in https://github.com/containerd/cri I wanted to add the bandwidth capalibity to the go-cni plugin.

Add support for bandwidth capability

---

README.md

1. Improve readme, make golang syntax highlight
2. Add a blank in the sample code to follow code style.

Improve readme, golang syntax highlight

---

cni.go
cni_test.go
namespace.go
vendor.conf
vendor/github.com/containernetworking/cni/README.md
vendor/github.com/containernetworking/cni/libcni/api.go
vendor/github.com/containernetworking/cni/libcni/conf.go
vendor/github.com/containernetworking/cni/pkg/invoke/args.go
vendor/github.com/containernetworking/cni/pkg/invoke/delegate.go
vendor/github.com/containernetworking/cni/pkg/invoke/exec.go
vendor/github.com/containernetworking/cni/pkg/invoke/os_unix.go
vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
vendor/github.com/containernetworking/cni/pkg/types/020/types.go
vendor/github.com/containernetworking/cni/pkg/types/current/types.go
vendor/github.com/containernetworking/cni/pkg/types/types.go
vendor/github.com/containernetworking/cni/pkg/version/plugin.go
vendor/github.com/containernetworking/cni/pkg/version/version.go

This introduces some API backwards incompat in reguards to the method
signatures adding the ability to pass a `context.Context` to CNI calls.
Closes #38 
Closes #46 
Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

Update to cni v0.7.1

---

namespace_opts.go
types.go

For https://github.com/containerd/cri/issues/1243.
This has been supported in Kubernetes dockershim and is required for Windows container support https://github.com/kubernetes/kubernetes/pull/67435
Signed-off-by: Lantao Liu <lantaol@google.com>

Add DNS capabilities.

---

opts.go

This PR attempts to follow existing patterns for CNIOpts and allows a conf list to be specified by a `[]byte`.

add WithConfList opt for adding conf list from bytes

---

README.md

This helps developers like myself with finding out what functions
and public APIs are available within the library, without checking
the code out in an IDE.
Generated from:
https://godoc.org/github.com/containerd/go-cni?tools
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>

Add GoDoc to README

---

cni_test.go
go.mod
go.sum
vendor/github.com/containernetworking/cni/libcni/api.go
vendor/github.com/containernetworking/cni/libcni/conf.go
vendor/github.com/containernetworking/cni/pkg/invoke/args.go
vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
vendor/github.com/containernetworking/cni/pkg/types/020/types.go
vendor/github.com/containernetworking/cni/pkg/types/args.go
vendor/github.com/containernetworking/cni/pkg/types/current/types.go
vendor/github.com/containernetworking/cni/pkg/types/types.go
vendor/github.com/containernetworking/cni/pkg/utils/utils.go
vendor/modules.txt

last tagged release of this module was 0.7.1, however,
there are more than 100 commits between master and
that tag:
~/go/src/github.com/containernetworking/cni$ git log --pretty=oneline
master...v0.7.1 | wc
104     760    9234
Since this project does not seems to follow a release cadence, we
should keep tracking the mater branch to benefit from the last
fixes and improvements.
Signed-off-by: Antonio Ojea <antonio.ojea.garcia@gmail.com>

bump containernetworking/cni to v0.8.0

---

.github/workflows/ci.yml
.golangci.yml
README.md
cni_test.go
opts.go
result.go

obsoletes https://github.com/containerd/go-cni/pull/61

Move CI to use GitHub Actions

---

cni.go
deprecated.go
opts.go
result.go

follow-up to https://github.com/containerd/go-cni/pull/63
To address golint;
opts.go:27:6: type name will be used as cni.CNIOpt by other packages, and that stutters; consider calling this Opt (golint)
type CNIOpt func(c *libcni) error
^
result.go:32:6: type name will be used as cni.CNIResult by other packages, and that stutters; consider calling this Result (golint)
type CNIResult struct {
^
The old names are kept for backward compatiblity (as this module is already past v1.0.0)

Rename/deprecate CNIOpt, CNIResult, CNI.GetCNIResultFromResults

---

result.go

- gocni.Result: results of multiple networks are mixed up
- gocni.Result.Raw (new): the raw results of multiple networks, without mixing up
Will be used for multi-networking support of nerdctl. (https://github.com/containerd/nerdctl/pull/189)

result: expose raw result

---

cni.go

Run setup on the networks in parallel.. partial address of #6
On average I'm seeing an approximate 30% reduction in cni setup duration by running the cni network attach requests in parallel.
```
DEBU[2021-12-06T13:31:36.258694903-06:00] begin cni setup                               podsandboxid=c2201c8869e4974f31e9dd59f991935243eec0f4ef7fb25d8173caabce42251d
DEBU[2021-12-06T13:31:38.307254529-06:00] cni result: {"Interfaces":{"cni0":{"IPConfigs":null,"Mac":"ea:78:3c:3a:aa:a9","Sandbox":""},
"eth0":{"IPConfigs":[{"IP":"10.88.0.233","Gateway":"10.88.0.1"},{"IP":"2001:4860:4860::e9","Gateway":"2001:4860:4860::1"}],"Mac":"b2:a1:c0:16:d5:e2","Sandbox":"/var/run/netns/cni-51d91578-476f-c880-270f-3c16ebe5997f"},
"lo":{"IPConfigs":[{"IP":"127.0.0.1","Gateway":""},{"IP":"::1","Gateway":""}],"Mac":" …
```

run setup on networks in parallel

---

opts.go

Follow-up: #82
Signed-off-by: Wei Fu <fuweid89@gmail.com>

init exec when create CNIConfig

---

opts.go

We missed this when adding the CHECK code to go-cni. @mikebrow and I have been talking about how we can move forward with this. We decided to update the version and come up with a plan to possibly remove this with the goal to be explicitly added. This is also a conversation the CNI maintainers have had as well! More to come!

Fix Loopback Version

---

script/install-cni

https://github.com/containernetworking/plugins/compare/v1.0.1...v1.1.1
Moving up to test with latest plugins, and esp. the duplicate address detection (dad) change.
Signed-off-by: Mike Brown <brownwm@us.ibm.com>

moving up to latest CNI plugin release

---

.github/workflows/ci.yml
.golangci.yml
deprecated.go

Signed-off-by: Wang Bing <wangbing.adam@gmail.com>
The linter 'golint' is deprecated (since v1.41.0).ref: https://github.com/golangci/golangci-lint/issues/1892

Use revive instead of golint

---

.github/workflows/ci.yml
Makefile
integration/cni_setup_teardown_linux_test.go

A follow up on https://github.com/containerd/go-cni/pull/99 to add in some serial setup buckets..
Also made a couple nits to the makefile..
Signed-off-by: Mike Brown <brownwm@us.ibm.com>

add in some serial setup tests; a little make cleanup

---

.github/workflows/ci.yml
.golangci.yml
result.go

Update golanci/golangci-lint package from v1.45.2 to v1.50.1. Run go fmt on package.
Remove deprecated linters.
Signed-off-by: Austin Vazquez <macedonv@amazon.com>

Update golangci/golangci-lint package

---

integration/cni_setup_teardown_linux_test.go
testutils.go

io/ioutil has been marked deprecated in Go 1.16.
Signed-off-by: Austin Vazquez <macedonv@amazon.com>

Remove references to io/ioutil package

---

go.mod
go.sum
integration/go.mod
integration/go.sum

https://github.com/containernetworking/cni/compare/v1.1.1...v1.1.2
Let's release v1.1.8 after merging this

go.mod: github.com/containernetworking/cni v1.1.2

---

namespace_opts.go

There is a new capability arg, cgroupPath, which is the relative cgroup path of the container.
Ref: https://github.com/containernetworking/cni/pull/936
Signed-off-by: Casey Callendrello <cdc@isovalent.com>

opts: add cgroupPath capability

---

.github/workflows/ci.yml
go.mod

Updates containerd/project-checks to v1.1.0 to run with Go 1.20. Updates
golangci/golangci-lint to v1.51.1 for Go 1.20 support. Adds Go 1.20 to
lint and test steps. Bumps minimum required version to Go 1.19
Signed-off-by: Austin Vazquez <macedonv@amazon.com>

Add Go 1.20 support

---

.github/workflows/ci.yml
README.md

Currently CI is broken with lint failures, as proved by trivial doc commits, for example https://github.com/containerd/go-cni/actions/runs/11523576454/job/32081885304
This PR updates the `setup-go`, `checkout` and `golangci-lint-action` versions to match those in the containerd repo. This fixes the issue.

Bump github actions dependencies to match containerd CI repo and fix lint

---

cni.go
cni_test.go
testutils.go

We are implementing the CNI Status verb. The Status verb is to provide the container runtime the ability to determine if the runtime should call CNI ADD. 
Please merge https://github.com/containerd/go-cni/pull/122 first
Reference:
ocicni (https://github.com/cri-o/ocicni/pull/196)

Support CNI STATUS Verb

---

cni.go
cni_test.go
deprecated.go
go.mod
go.sum
integration/go.mod
integration/go.sum
mutex.go
mutex_deadlocks.go
result.go
testutils.go

There were at least two code paths which might acquire `.RLock()` recursively:
1. `Setup*()` -> `createResult()`
2. `Setup*()` -> `Networks()`.
On its own, it's not a problem, but if `.Load()` is called concurrently, it might do `.Lock()` in between recursive `.RLock()`s, which would lead to a deadlock.
See #125
Fix by introducing a contract on the way mutex is acquired.
Add a test facility to verify for such mistakes via build tags:
* `go test -race` or `go test -tags deadlocks` activates deadlock detection

fix: recursive RLock() mutex acquision
